config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  resources :restored_objects do
    resources :build, controller: 'restored_objects/build'
  end

  resources :categories
  resources :collections

  devise_for :users
  get '/admin' => 'users#admin', as: :admin_panel
  get '/:username' => 'users#show', as: :user_by_name
  get 'users/:id' => 'users#show', as: :user

  post 'users/:id/approve' => 'users#approve', as: :approve_user
  post 'users/:id/deny' => 'users#deny', as: :deny_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
    root 'home#index'
  end
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :collections_restored_objects
  has_many :restored_objects, through: :collections_restored_objects

  accepts_nested_attributes_for :collections_restored_objects, allow_destroy: true

  belongs_to :user

  validate :needs_objects

  has_one_attached :avatar

  def featured_image
    if self.avatar.attached?
      self.avatar.service_url
    else
      '/object.svg'
    end
  end

  def add_visit
    self.visits += 1
    self.save
  end

  private

  def needs_objects
    if collections_restored_objects.size == 0
      errors.add(:restored_objects, I18n.t('collections.needs_objects_error'))
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
    @collections  = Collection.all
    authorize @collections
  end

  def show
    @collection  = Collection.find(params[:id])
    authorize @collection
    @collection.add_visit

    @objects   = @collection.restored_objects.page params[:page]
  end

  def new
    @collection = Collection.new
    authorize @collection
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user_id = current_user.id

    print collection_params
      

    authorize @collection
    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection }
        format.json do
          render :show,
                 status: :created, location: @collection
        end
      else
        format.html { render :new }
        format.json do
          render json: @collection.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @collection  = Collection.find(params[:id])
    authorize @collection
  end

  def update
    @collection = Collection.find(params[:id])
    authorize @collection
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection }
        format.json do
          render :show,
                 status: :created, location: @collection
        end
      else
        format.html { render :new }
        format.json do
          render json: @collection.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @collection = Collection.find(params[:id])
    authorize @collection
    @collection.destroy
    redirect_to(collections_path)
  end

  private

  def collection_params
    params.require(:collection).permit(:title, :description, :avatar,
      collections_restored_objects_attributes: [:id, :collection_id, :restored_object_id, :_destroy])
  end

end

app/views/collections/_collections_restored_object_fields.html.erb
<div class="nested-fields card mb-2">
    <div class="card-body">
        <%= f.label t('activerecord.models.restored_object.one') %><br/>
        <%= f.select :restored_object_id, current_user.restored_objects.where(current_step: 'active').collect {|u| [u.title, u.id]}, {}, {class: 'form-control'} %>
        <%= f.hidden_field :collection_id, value: @collection.id %>
        <br/>
        <%= link_to_remove_association f, {class:'btn btn-danger', aria: {label: t("collections.remove")}} do t("collections.remove") end %>
    </div>
    <br/>
</div>

app/views/collections/edit.html.erb
<div class="container">
    <h1><%= t('collections.edit') %></h1>

    <%= form_for(@collection, :html => { multipart: true }) do |f| %>

        <% if @collection.errors.any? %>
            <div class="alert alert-danger">
                <ul>
                <% @collection.errors.full_messages.each do |msg| %>
                    <li><%= msg %>
                <% end %>
                </ul>
            </div>
        <% end %>

        <%= f.label :title %><br/>
        <%= f.text_field :title, required: true, class: 'form-control' %>
        <br/>
        <%= f.label :description %><br/>
        <%= f.text_area :description, required: true, class: 'form-control' %>
        <br/>
        <%= f.label :avatar %>
        <%= f.file_field :avatar %><br/>
        <br/>

        <div id="collections_restored_objects field">
            <h2><%= t('collections.restored_objects')%></h2>
            <br/>

            <div class="card-columns">
                <%= f.fields_for :collections_restored_objects do |h| %>
                    <div class="card">
                    <div class="field card-body center">
                        <p><%= h.object.restored_object.title %><p>
                        <%= h.check_box :_destroy %>
                        <%= h.label :_destroy %>
                    </div>
                    </div>
                <% end %>
            </div>
            <br/>

            <div class="links">
                <%= link_to_add_association f, :collections_restored_objects do %> <%= t('collections.add_restored_objects') %> <% end %>
            </div>
        </div>
        <br/>
        <%= f.submit t('collections.save'), class:'btn btn-primary' %>
    <% end %>
</div>

app/views/collections/index.html.erb
<div class="container mt-4">
  <% if policy(Collection).create? %>
    <%= link_to t('collections.add'), new_collection_path, class: 'btn btn-primary right' %>
  <% end %>
  <br/>
  <% @collections.each.with_index do |collection, i| %>
    <%= link_to collection do %>
      <div class="collection mt-2">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <h2 class="card-title">
            <%= collection.title %>
            <span class="badge badge-pill badge-info">
              <%= collection.restored_objects.count %> <%= t('collections.restored_objects') %>
            </span>
          </h2>
            <p><%= collection.description.html_safe %></p>
            <p class="owner"><%= link_to collection.user.name, collection.user %></p>
          </div>
          <div class="col-xs-12 col-md-6 center">
            <%= image_tag(collection.featured_image) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/collections/new.html.erb
<div class="container">
    <h1><%= t('collections.add') %></h1>

    <div class="alert alert-info">
        <p><%= t('collections.p1').html_safe %></p>
        <p><%= t('collections.p2').html_safe %></p>
    </div>

    <%= form_for(@collection, :html => { multipart: true }) do |f| %>

        <% if @collection.errors.any? %>
            <div class="alert alert-danger">
                <ul>
                <% @collection.errors.full_messages.each do |msg| %>
                    <li><%= msg %>
                <% end %>
                </ul>
            </div>
        <% end %>

        <%= f.label :title %><br/>
        <%= f.text_field :title, required: true, class: 'form-control' %>
        <br/>
        <%= f.label :description %><br/>
        <%= f.text_area :description, required: true, class: 'form-control' %>
        <br/>
        <%= f.label :avatar %>
        <%= f.file_field :avatar %><br/>
        <br/>

        <div id="collections_restored_objects field">
            <h2><%= t('collections.restored_objects')%></h2>
            <br/>
            <div class="links">
                <%= link_to_add_association f, :collections_restored_objects do %> <%= t('collections.add_restored_objects') %> <% end %>
            </div>
        </div>
        <br/>
        <%= f.submit t('collections.save'), class:'btn btn-primary' %>
    <% end %>
</div>

app/views/collections/show.html.erb
<div class="profile-header">
  <%= image_tag @collection.user.header_image, class: 'profile-header-img' %>
</div>
<div class="container">
  <% if policy(@collection).update? %>
    <%= link_to t('shared.update'), edit_collection_path(@collection), class: 'btn btn-primary right' %>
  <% end %>
  <% if policy(@collection).destroy? %>
    <%= link_to t('shared.destroy'), collection_path(@collection), method: :delete, class: 'btn btn-danger right mr-2' %>
  <% end %>
  <%= image_tag @collection.user.avatar_image, class: 'avatar' %>
  <h1 style="display: inline"><%= @collection.title %></h1>
  <br/><br/>
  <p><%= link_to @collection.user.name, @collection.user %></p>
  <br/>
  <p><%= @collection.description %></p>
  <br/>
  <div class="card-columns">
      <% @objects.each do |obj| %>
        <%= link_to obj do %>
          <div class="card">
            <%= link_to image_tag(obj.featured_image, class:'card-img-top'), obj %>
            <div class="card-body">
                <span class="badge badge-pill badge-info float-right"><%= obj.pieces.count %> <%= t('restored_object.pieces') %></span>
                <h2><%= link_to obj.title, obj, data: { no_turbolink: true } %></h2>
                <p><%= truncate(obj.description, length: 150, omission: "...") %>
            </div>
            <div class="card-footer">
                <%= time_ago_in_words obj.created_at %><br/>
                <% obj.categories.each do |cat| %>
                    <%= link_to cat do %>
                        <span class="badge badge-pill badge-secondary"><%= cat.name %></span>
                    <% end %>
                <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
  <br/><br/>
  <%= paginate @objects, theme: 'twitter-bootstrap-4' %>
</div>