config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  resources :restored_objects do
    resources :build, controller: 'restored_objects/build'
  end

  resources :categories
  resources :collections

  devise_for :users
  get '/admin' => 'users#admin', as: :admin_panel
  get '/:username' => 'users#show', as: :user_by_name
  get 'users/:id' => 'users#show', as: :user

  post 'users/:id/approve' => 'users#approve', as: :approve_user
  post 'users/:id/deny' => 'users#deny', as: :deny_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
    root 'home#index'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restored_objects
  has_many :collections

  has_one_attached :avatar
  
  has_one_attached :header

  validate :correct_attachments_mime_types

  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates_uniqueness_of :username

  after_create :send_mail_to_admin

  def header_image
    if header.attached?
      header.service_url
    else
      '/header.png'
    end
  end

  def avatar_image
    if avatar.attached?
      avatar.service_url
    else
      '/user.svg'
    end
  end

  private

  def correct_attachments_mime_types
    if header.attached? && !header.content_type.in?(%w(image/png image/bmp image/jpg image/jpeg image/tiff))
      errors.add(:header, "Must be an image file.")
    end

    if avatar.attached? && !avatar.content_type.in?(%w(image/png image/bmp image/jpg image/jpeg image/tiff))
      errors.add(:header, "Must be an image file.")
    end
  end

  def send_mail_to_admin
    AdminMailer.new_registration(email).deliver
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if params[:id]
      @user = User.find(params[:id])
    elsif params[:username]
      @user = User.where(username: params[:username]).first
    end
  end

  def admin
    if !current_user || !current_user.admin
      flash[:danger] = t('shared.not_authorized')
      redirect_to root_path
    end
    @candidates = User.where(approved: false)
  end

  def isObjectFromUser(obj)
    return current_user == obj.user
  end

  helper_method :isObjectFromUser

  def create
    @user = User.create(user_params)
  end

  def approve
    @user = User.find(params[:id])
    
    if !current_user || !current_user.admin
      flash[:danger] = t('shared.not_authorized')
      redirect_to root_path
    end

    @user.update(approved: :true)
    flash[:notice] = t('users.approved', user: @user.username)
    redirect_to :admin_panel
  end

  def deny
    @user = User.find(params[:id])
    
    if !current_user || !current_user.admin || @user.approved 
      flash[:danger] = t('shared.not_authorized')
      redirect_to root_path
    end

    @user.destroy!
    flash[:notice] = t('users.denied', user: @user.username)
    redirect_to :admin_panel
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:avatar, :approved)
  end

end

app/views/users/admin.html.erb
<div class="profile-header">
  <%= image_tag current_user.header_image, class: 'profile-header-img' %>
</div>
<div class="container">
    <h1>Admin panel</h1>
    <br/>
    <div class="card-group">
        <div class="card col-xs-12 col-md-4" >
            <div class="card-body">
                <h4 class="card-title"><%= t 'activerecord.models.user.other' %></h4>
                <h5 class="display-4 text-info"><%= User.all.count %></h5>
            </div>
        </div>
        <div class="card col-xs-12 col-md-4" >
            <div class="card-body">
                <h4 class="card-title"><%= t 'activerecord.models.restored_object.other' %></h4>
                <h5 class="display-4 text-info"><%= RestoredObject.where(current_step: :active).count %></h5>
            </div>
        </div>
        <div class="card col-xs-12 col-md-4" >
            <div class="card-body">
                <h4 class="card-title"><%= t 'activerecord.models.collection.other' %></h4>
                <h5 class="display-4 text-info"><%= Collection.all.count %></h5>
            </div>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
    <h2 class="mb-4"><%= t('admin.candidates') %></h2>
    
    <% if @candidates.count > 0 %>
        <table class="table">
        <tr>
            <th><%= t('activerecord.attributes.user.name') %></th>
            <th><%= t('activerecord.attributes.user.username') %></th>
            <th>Email</th>
            <th><%= t('activerecord.attributes.user.sign_up_date') %></th>
            <th></th>
        </tr>
        <% @candidates.each do |u| %>
            <tr>
                <td><%= link_to u.name, u %></td>
                <td><%= link_to u.username, u %></td>
                <td><%= link_to u.email, u %></td>
                <td><%= time_ago_in_words u.created_at %></td>
                <td><%= link_to t('admin.approve'), approve_user_path(u), method: :update %> | <%= link_to t('admin.deny'), deny_user_path(u), method: :update  %></td>
            </tr>
        <% end %>
        </table>
    <% else %>
        <p><%= t('admin.no_candidates') %></p>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="profile-header">
  <%= image_tag @user.header_image, class: 'profile-header-img' %>
</div>
<div class="container">
  <div class="text-right">
    <% if policy(RestoredObject).create? %>
      <%= link_to t('restored_object.add_object'), new_restored_object_path, class: 'btn btn-primary' %>
    <% end %>
    <% if policy(Collection).create? %>
      <%= link_to t('collections.add'), new_collection_path, class: 'btn btn-primary' %>
    <% end %>
    <% if current_user&.id == @user.id  %>
      <%= link_to t('users.edit_settings'), edit_user_registration_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="user-header">
    <h2 style="display: inline">
      <%= image_tag @user.avatar_image, class: 'avatar' %>
      <%= @user.name %>
    </h2>
  </div>
  <br/>
  <% if !(@user.bio.blank?) %>
    <div class="row container mb-4">
      <p><%= @user.bio.html_safe %></p>
    </div>
  <% end %>
</div>
<% if @user.collections.count > 0 %>
  <section class="blue">
    <div class="container">
      <div class="card-columns">
        <% @user.collections.each_with_index do |obj, index| %>
          <div class="card">
            <div class="card-body">
                <span class="badge badge-pill badge-info float-right"><%= obj.restored_objects.count %> <%= t('restored_object.pieces') %></span>
                <h2><%= link_to obj.title.capitalize, obj, data: { no_turbolink: true } %></h2>
                <p><%= truncate(obj.description, length: 150, omission: "...").capitalize %></p>
                <%= link_to obj.user.name, obj.user %><br/>
                <%= time_ago_in_words obj.created_at %> | <%= obj.visits %> <%= t('shared.visits') %><br>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
<% end %>
<div class="container">
  <div class="card-columns">
    <% @user.restored_objects.where(current_step:'active').each_with_index do |obj, index| %>
      <div class="card">
        <%= link_to image_tag(obj.featured_image, class:'card-img-top'), obj %>
          <div class="card-body">
              <span class="badge badge-pill badge-info float-right"><%= obj.pieces.count %> <%= t('restored_object.pieces') %></span>
              <% obj.categories.each do |cat| %>
                <%= link_to cat do %>
                    <span class="badge badge-pill badge-secondary"><%= cat.name.capitalize %></span>
                <% end %>
              <% end %>
              <h2><%= link_to obj.title.capitalize, obj, data: { no_turbolink: true } %></h2>
              <p><%= truncate(obj.description, length: 150, omission: "...").capitalize %></p>
              <%= time_ago_in_words obj.created_at %> | <%= obj.visits %> <%= t('shared.visits') %><br>
          </div>
          <% if isObjectFromUser(obj) %>
            <div class="card-footer right">
               <%= link_to edit_restored_object_path(obj), class:'btn btn-primary mr-2' do %>
                  <img src="/edit.svg" style="width: 1em;" />
                <% end %>
                <%= link_to obj , data: {:confirm => 'Are you sure?'}, method: :delete, class:'btn btn-danger' do %>
                  <img src="/trash.svg" style="width: 1em;"/>
                <% end %>
                <br/><br/>
            </div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>