config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  resources :restored_objects do
    resources :build, controller: 'restored_objects/build'
  end

  resources :categories
  resources :collections

  devise_for :users
  get '/admin' => 'users#admin', as: :admin_panel
  get '/:username' => 'users#show', as: :user_by_name
  get 'users/:id' => 'users#show', as: :user

  post 'users/:id/approve' => 'users#approve', as: :approve_user
  post 'users/:id/deny' => 'users#deny', as: :deny_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
    root 'home#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_restored_objects
  has_many :restored_objects, through: :categories_restored_objects

  def i18n_name
    if I18n.locale == :es
      return nombre
    else
      return name
    end
  end
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :collections_restored_objects
  has_many :restored_objects, through: :collections_restored_objects

  accepts_nested_attributes_for :collections_restored_objects, allow_destroy: true

  belongs_to :user

  validate :needs_objects

  has_one_attached :avatar

  def featured_image
    if self.avatar.attached?
      self.avatar.service_url
    else
      '/object.svg'
    end
  end

  def add_visit
    self.visits += 1
    self.save
  end

  private

  def needs_objects
    if collections_restored_objects.size == 0
      errors.add(:restored_objects, I18n.t('collections.needs_objects_error'))
    end
  end
end

app/models/composition.rb
class Composition < ApplicationRecord
  belongs_to :material
  belongs_to :restored_object
end

app/models/deterioration.rb
class Deterioration < ApplicationRecord
  has_many :deteriorations_restored_objects
  has_many :restored_objects, through: :deteriorations_restored_objects

  def i18n_name
    if I18n.locale == :es
      return nombre
    else
      return name
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :compositions
  has_many :restored_objects, through: :compositions

  def i18n_name
    if I18n.locale == :es
      return nombre
    else
      return name
    end
  end
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :restored_object

  has_one_attached :model
  has_one_attached :material
  has_many_attached :images
end

app/models/priority.rb
class Priority < ApplicationRecord
  has_many :restored_objects

  def i18n_name
    if I18n.locale == :es
      return nombre
    else
      return name
    end
  end
end

app/models/protection.rb
class Protection < ApplicationRecord
  has_many :restored_objects

  def i18n_name
    if I18n.locale == :es
      return nombre
    else
      return name
    end
  end
end

app/models/restored_object.rb
class RestoredObject < ApplicationRecord
  belongs_to :user

  belongs_to :priority, optional: true
  belongs_to :protection, optional: true

  has_many :categories_restored_objects, dependent: :destroy
  has_many :categories, through: :categories_restored_objects

  has_many :deteriorations_restored_objects, dependent: :destroy
  has_many :deteriorations, through: :deteriorations_restored_objects

  belongs_to :state, optional: true

  belongs_to :units, optional: true

  # TODO: MUST DEPEND ON STEP
  validates :priority_id, presence: true, if: :active?
  validates :protection_id, presence: true, if: :active?
  validates :state_id, presence: true, if: :active?
  validates :units_id, presence: true, if: :active?

  has_many :pieces

  has_many :compositions
  has_many :materials, through: :compositions

  has_many :collections_restored_objects
  has_many :collections, through: :collections_restored_objects

  #validates :title, :description, presence: true

  accepts_nested_attributes_for :pieces, allow_destroy: true

  geocoded_by :address
  after_validation :geocode

  enum object_type: [ :ply, :obj, :stl, :other ]

  has_one_attached :avatar

  def steps
    %w[basic unique pieces restoration details]
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
    self.current_step == steps.first
  end

  def last_step?
    self.current_step == steps.last
  end

  def all_valid?
    steps.all? do |step|
      self.current_step = step
    valid?
    end
  end

  def active?
    self.current_step == 'active'
  end

  def featured_image
    if self.avatar.attached?
      self.avatar.service_url
    else
      '/object.svg'
    end
  end

  def add_visit
    self.visits += 1
    self.save
  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :restored_objects

  def i18n_name
    if I18n.locale == :es
      return nombre
    else
      return name
    end
  end
end

app/models/units.rb
class Units < ApplicationRecord
  has_many :restored_objects
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restored_objects
  has_many :collections

  has_one_attached :avatar
  
  has_one_attached :header

  validate :correct_attachments_mime_types

  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates_uniqueness_of :username

  after_create :send_mail_to_admin

  def header_image
    if header.attached?
      header.service_url
    else
      '/header.png'
    end
  end

  def avatar_image
    if avatar.attached?
      avatar.service_url
    else
      '/user.svg'
    end
  end

  private

  def correct_attachments_mime_types
    if header.attached? && !header.content_type.in?(%w(image/png image/bmp image/jpg image/jpeg image/tiff))
      errors.add(:header, "Must be an image file.")
    end

    if avatar.attached? && !avatar.content_type.in?(%w(image/png image/bmp image/jpg image/jpeg image/tiff))
      errors.add(:header, "Must be an image file.")
    end
  end

  def send_mail_to_admin
    AdminMailer.new_registration(email).deliver
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @featured = RestoredObject.first(3)
    @featured_museum = User.last
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def show
      @first_half = "hi"
    end

    def admin
      @first_half = "hi"
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if params[:id]
      @user = User.find(params[:id])
    elsif params[:username]
      @user = User.where(username: params[:username]).first
    end
  end

  def admin
    if !current_user || !current_user.admin
      flash[:danger] = t('shared.not_authorized')
      redirect_to root_path
    end
    @candidates = User.where(approved: false)
  end

  def isObjectFromUser(obj)
    return current_user == obj.user
  end

  helper_method :isObjectFromUser

  def create
    @user = User.create(user_params)
  end

  def approve
    @user = User.find(params[:id])
    
    if !current_user || !current_user.admin
      flash[:danger] = t('shared.not_authorized')
      redirect_to root_path
    end

    @user.update(approved: :true)
    flash[:notice] = t('users.approved', user: @user.username)
    redirect_to :admin_panel
  end

  def deny
    @user = User.find(params[:id])
    
    if !current_user || !current_user.admin || @user.approved 
      flash[:danger] = t('shared.not_authorized')
      redirect_to root_path
    end

    @user.destroy!
    flash[:notice] = t('users.denied', user: @user.username)
    redirect_to :admin_panel
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:avatar, :approved)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Determines flash alerts css class based on the level parameter
  def flash_class(level)
    case level
    when 'notice' then 'info'
    when 'success' then 'success'
    when 'alert' then 'warning'
    else 'danger'
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FragmentX</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#0005fb">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/"><img src="/logo-mini.svg"/></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to t('nav_bar.home') , root_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('nav_bar.restored_objects') , restored_objects_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('nav_bar.collections') , collections_path, class:'nav-link' %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              🌍
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to url_for(locale: :es), {class: "nav-link ul"} do %> 🇪🇸 Castellano<% end %>
              <%= link_to url_for(locale: :en), {class: "nav-link ul"} do %> 🇺🇸 English<% end %>
            </div>
          </li>
          <% if !(user_signed_in?) %>
            <li class="nav-item">
              <%= link_to t('nav_bar.sign_in'), new_user_session_path, class:'nav-link' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Dashboard' , user_path(current_user.id), class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "/logout", {class: "nav-link"} do %><%= I18n.t 'nav_bar.sign_out' %><% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= flash_class(key) %>" role="alert">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
    <footer>
      <div class="container center">
        FragmentX 2018 - 2020<br/>
        Icons by Made, Dinosoft Labs, and SBTS from the Noun Project
        <br/><br/><br/>
        <div class="logos">
          <div><img src="/upv.jpg"/></div>
          <div><img src="/ai2.png"/></div>
          <div><img src="/feder.png"/></div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/threejs.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FragmentX</title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#0005fb">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <div id="loader" class="loader"><img src="/loading.svg"/> <%= t('restored_object.viewer.loading_text') %></div>
    <%= yield %>
  </body>
</html>